### ISSUE TITLE
Update Meteor & packages

### ISSUE THREAD

**Issue by Dandandan** [hckrs/hckrs.io#102]
The current version is 1.0.2, we probably should update to a newer version & test it. It makes probably sense to wait for the almost-ready 1.0.4, as this also improves performance for us, and so far I know the previous releases didn't include serious security fixes.

**Comment by Dandandan** [comment]
Close this one as it got merged, Meteor 1.1 is out already btw ;).

**Comment by ramshorst** [comment]
Cool :)
