### ISSUE TITLE
hckr location.

### ISSUE THREAD

**Issue by ClemensGrunewald** [hckrs/hckrs.io#108]
Hey Guys,
first of all, great job. Keep on going the awesome work! :)
I registered myself some minutes ago, but unfortunately I did it in the wrong city. I searched for a way to change it to the right location but it seems to be impossible to change it as a normal user without access to the database. 
I think, changing basic user information like the e-mail adress, hacking skills or hacking location should be possible for everyone. So think about it and decide :)

Thanks a lot for possible future experiences,
Clee

**Comment by ramshorst** [comment]
Thank you for your feedback!
This is already possible, click your profile image and then your name. The only thing you cannot change is your city. I did that for you though! Thanks,
Toon

**Comment by JarnoLeConte** [comment]
Maybe we should allow this in the future. The actual question is if users are allowed to change city whenever they like? If we would prevent from this we must implement some restrictions.

**Comment by ramshorst** [comment]
One solution would be allowing user to only change city twice ; but it would be hard to understand and to build. I think we could put an email link that allows you to writer to an ambassador from your profile ? Is that a good solution ?

**Comment by JarnoLeConte** [comment]
It's not persé hard to build, but the email link is the easiest solution of course ^^

**Comment by ramshorst** [comment]
Let’s do the email link then :)

**Comment by ramshorst** [comment]
Who want's to do this?
