### ISSUE TITLE
Warning from ghostery

### ISSUE THREAD

**Issue by MartinDelille** [hckrs/hckrs.io#109]
My https://www.ghostery.com firefox plugin is warning me about cross site script:
![capture d ecran 2015-03-16 18 10 35](https://cloud.githubusercontent.com/assets/879889/6671800/18f520ee-cc08-11e4-80e4-0c4c6693c9b7.png)
Basic twitter and facebook button track user across website whitch is not fine for individual freedom. There must be a way to get away from these warning easily!

**Comment by ramshorst** [comment]
Thanks Martin :) 
You think there is an other way of implementing the button that avoids the Facebook message and the twitter messages ?

**Comment by ramshorst** [comment]
I wonder if the is avoidable though. Maybe if the go trough the social API of each service, and use this solution a backup in case the user does not have the given social service connected in his profile.

**Comment by MartinDelille** [comment]
This website use none intrusive social network button: http://philippe.scoffoni.net/

**Comment by ramshorst** [comment]
example URL : http://philippe.scoffoni.net/diaporama-logiciels-libres-tpe/
This sharing requires connecting first, what would be ok but is somewhat more complicated to build. We should move to a system like this in the future i guess :)
