### ISSUE TITLE
The login buttons are not displayed in the right way in Safari

### ISSUE THREAD

**Issue by jimtolman** [hckrs/hckrs.io#113]
See the screenshots. 
http://i.imgur.com/pUuY4yy.jpg
http://i.imgur.com/U4FjUrd.png

**Comment by ramshorst** [comment]
What safari version is that?

**Comment by jimtolman** [comment]
Version 8.0.3 (10600.3.18)

**Comment by ramshorst** [comment]
Weird! Maybe it’s a SVG export version thing. Let me check...

**Comment by Dandandan** [comment]
Maybe related: the hckrs logo renders weird on firefox.
![screenshot from 2015-04-03 18 30 10](https://cloud.githubusercontent.com/assets/163737/6985076/86af17a4-da2f-11e4-9e96-1a193821b970.png)

**Comment by Dandandan** [comment]
(Ubuntu 14.04, Firefox Developer Edition)

**Comment by ramshorst** [comment]
@Dandandan, @jimtolman are these issues still visible in current browsers ?
