### ISSUE TITLE
Native language on profile

### ISSUE THREAD

**Issue by jimtolman** [hckrs/hckrs.io#119]
Wouldn't it be nice to be able to add you mother tongue to your profile, even though all main communication will be in English?

**Comment by ramshorst** [comment]
Your idea is that you could for example find dutch people in honking or things like that ? :)

**Comment by jimtolman** [comment]
Yes. Or not adding languages as skills (like on LinkedIn), yet only adding your mother tongue so when someone for example organises a meetup, they know that they have a Mandarin speaking audience.
