### ISSUE TITLE
Add Hong Kong as a city

### ISSUE THREAD

**Issue by daanvr** [hckrs/hckrs.io#120]
@mtenpas hacker from Enschede, is now living in Hong Kong and would be interested in starting a community there =)

This means we should probably add Hong Kong to the list of cities =)
@ramshorst

**Comment by ramshorst** [comment]
The city is added. The will be online with the next release (date not set yet). We could also do realease before if needed.
I also made here an email adresse (michelle@hckrs.io) and a forward from hongkong@hckrs.io. And the twitter account is set up :)

**Comment by mtenpas** [comment]
Thank you @ramshorst! Do you already know when the next release will be? I might want to invite a couple of new hackers from Hong Kong soon, and it would be great if they could set HK as their location. ;)

**Comment by ramshorst** [comment]
No problem!
The code is comitted, so now that @jarnolecomte 's laptop is alive again maybe he can release it?
We are very curious that you will manage to do in Hong Kong!

**Comment by mtenpas** [comment]
@JarnoLeConte?  I think the tagging didn't work in @ramshorst comment above? ;)
