### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by MartinDelille** [hckrs/hckrs.io#124]
Performing the installation step 4, I had to type the following to run the server:

    ../tools/hckrs

without the *run* argument. Otherwise, there is no *hckrs* executable in the *web* folder.

**Comment by ramshorst** [comment]
I didn't fully get what you mean @MartinDelille, could you be more precise?

**Comment by MartinDelille** [comment]
I cannot reproduce.

**Comment by ramshorst** [comment]
Thank you for your time Martin :)
