### ISSUE TITLE
Suggestion inline svg

### ISSUE THREAD

**Issue by charifmews** [hckrs/hckrs.io#125]
I tested hckrs.io on:

http://tools.pingdom.com/fpt/#!/cncxMK/hckrs.io

There are 79 requests which can be like 60 if you use inline svg. Keep up the good work! 

https://css-tricks.com/using-svg/

**Comment by ramshorst** [comment]
Excellent! we will do that :) that might also help with some rendering issues we have!
Is doing so only interesting if you have one ocurence of the image? Or is there a trick for that?

Verstuurd vanaf mijn iPhone

**Comment by Dandandan** [comment]
Thanks for your suggestion!

I am not sure inlining SVGs will actually reduce page load time, they only contribute little to the total page load time. Not inlining them has a few advantages as well: they can be loaded lazily, in parallel and can be loaded from cache. Also we rely on the templating system from Meteor to load html / svg, so it will  increase the size of the generated JavaScript code.

**Comment by charifmews** [comment]
@Dandandan you are right for desktop, but especially on mobile you will see some difference in performance (the number of http-requests really count hard there (on desktop with a normal internet connection you will see no noticeable/minimal difference I think)). 

@ramshorst You can inline SVG in CSS and so you can have more than one occurrence of the image

**Comment by ramshorst** [comment]
Sounds good! Do you also agree @Dandandan that this is a step forward ?

@charifmews the CSS way sounds awesome indeed :)

**Comment by Dandandan** [comment]
TBH, I still don't think it's worth it, but I love to be proven otherwise :). CSS rendering is in most browser blocking BTW, so I am skeptical this would turn out to be a net win.

**Comment by JarnoLeConte** [comment]
Thinking a different way, is it possible to create a single sprite image containing all SVG's, the same as what you usually do when working met PNG's? 
This doesn't hold for SVG, right? Or maybe it does?

**Comment by ramshorst** [comment]
we could even make a font of it, any thoughts if that is better?

**Comment by Dandandan** [comment]
Interesting slide about this (anti-patterns in HTTP2, mentioned on Hacker News)

https://docs.google.com/presentation/d/1r7QXGYOLCh4fcUq0jDdDwKJWNqWK1o4xMtYpKZCJYjM/present?slide=id.p19
