### ISSUE TITLE
Make hckrs.io a community template

### ISSUE THREAD

**Issue by MartinDelille** [hckrs/hckrs.io#126]
hckrs.io design is great and I'd like to use it for another kind of community (http://www.ploss-ra.fr). Is the site compliant for fork and personnalisation?

**Comment by JarnoLeConte** [comment]
First of all, thank you for liking the hckrs.io. Great to hear that you see possibilities in this setup.  

To answer your question: Yes, it is allowed to fork and personalize as long you respect our license, which can be found in the root of this Repository. 

Although I would mention that hckrs.io isn't really a template or framework. It is not built to fork. Neither we planned this for the future.

What could be useful is using some of our packages, but again we don't focus on possibility to reuse packages in other applications. 

This is my short answer. Probably @Ramshorst can tell you a lot more about the possibilities.

**Comment by ramshorst** [comment]
Of course there is no objections to that.
One thing I would like to point out that te subculture release we are working on will allow users to build ‘subcultures’ in hckrs.io. At the bottom of this page are the designs (not definitive at all): https://github.com/hckrs/hckrs.io/issues/40
