### ISSUE TITLE
Den Bosch toevoegen aan de lijst met steden

### ISSUE THREAD

**Issue by daanvr** [hckrs/hckrs.io#129]
Er is iemand genaamd Daniël die graag de hackers community van den Bosch opzet. @ramshorst is all in contact met hem en hij weet inmiddels all wat beter wat het allemaal inhoud. Hij vind het leuk om maandelijks een meetup te organiseren.

#awesome

**Comment by ramshorst** [comment]
Only has 50 users on GibHub so not viable for a meetup now.
