### ISSUE TITLE
Couldn't start hckrs bin

### ISSUE THREAD

**Issue by rete** [hckrs/hckrs.io#141]
I have followed the instructions in the README.md file in order to run the hckrs bin :
- git clone https://github.com/hckrs/hckrs.io.git
- cd hckrs
- source ./tools/install.sh # everything goes well
- hckrs run

This last step prints the following message : 

remi [17:40:50] hckrs.io $ hckrs run
[[[[[ ~/hckrs.io ]]]]]                        

=> Started proxy.  
=> Meteor 1.2.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.  
W20151123-17:41:18.095(1)? (STDERR)  
W20151123-17:41:18.268(1)? (STDERR) /home/remi/.meteor/packages/meteor-tool/.1.0.45.10dec5p++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151123-17:41:18.268(1)? (STDERR)                             throw(ex);
W20151123-17:41:18.268(1)? (STDERR)                                   ^
W20151123-17:41:18.269(1)? (STDERR) Error: a route URL prefix must begin with a slash
W20151123-17:41:18.269(1)? (STDERR)     at [object Object]._.extend.declare (packages/routepolicy/routepolicy.js:95:1)
W20151123-17:41:18.269(1)? (STDERR)     at new StreamServer (packages/ddp/stream_server.js:16:1)
W20151123-17:41:18.269(1)? (STDERR)     at new Server (packages/ddp/livedata_server.js:1248:1)
W20151123-17:41:18.269(1)? (STDERR)     at Package (packages/ddp/server_convenience.js:19:1)
W20151123-17:41:18.269(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/packages/ddp.js:4768:4
W20151123-17:41:18.269(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/packages/ddp.js:4779:3
W20151123-17:41:18.269(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/boot.js:222:10
W20151123-17:41:18.269(1)? (STDERR)     at Array.forEach (native)
W20151123-17:41:18.269(1)? (STDERR)     at Function._.each._.forEach (/home/remi/.meteor/packages/meteor-tool/.1.0.45.10dec5p++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151123-17:41:18.270(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8  
W20151123-17:41:24.277(1)? (STDERR)  
W20151123-17:41:24.277(1)? (STDERR) /home/remi/.meteor/packages/meteor-tool/.1.0.45.10dec5p++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151123-17:41:24.277(1)? (STDERR)                             throw(ex);
W20151123-17:41:24.277(1)? (STDERR)                                   ^
W20151123-17:41:24.319(1)? (STDERR) Error: a route URL prefix must begin with a slash
W20151123-17:41:24.319(1)? (STDERR)     at [object Object]._.extend.declare (packages/routepolicy/routepolicy.js:95:1)
W20151123-17:41:24.319(1)? (STDERR)     at new StreamServer (packages/ddp/stream_server.js:16:1)
W20151123-17:41:24.319(1)? (STDERR)     at new Server (packages/ddp/livedata_server.js:1248:1)
W20151123-17:41:24.320(1)? (STDERR)     at Package (packages/ddp/server_convenience.js:19:1)
W20151123-17:41:24.320(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/packages/ddp.js:4768:4
W20151123-17:41:24.320(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/packages/ddp.js:4779:3
W20151123-17:41:24.320(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/boot.js:222:10
W20151123-17:41:24.320(1)? (STDERR)     at Array.forEach (native)
W20151123-17:41:24.320(1)? (STDERR)     at Function._.each._.forEach (/home/remi/.meteor/packages/meteor-tool/.1.0.45.10dec5p++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151123-17:41:24.320(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8  
W20151123-17:41:30.432(1)? (STDERR)  
W20151123-17:41:30.432(1)? (STDERR) /home/remi/.meteor/packages/meteor-tool/.1.0.45.10dec5p++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151123-17:41:30.433(1)? (STDERR)                             throw(ex);
W20151123-17:41:30.433(1)? (STDERR)                                   ^
W20151123-17:41:30.476(1)? (STDERR) Error: a route URL prefix must begin with a slash
W20151123-17:41:30.476(1)? (STDERR)     at [object Object]._.extend.declare (packages/routepolicy/routepolicy.js:95:1)
W20151123-17:41:30.476(1)? (STDERR)     at new StreamServer (packages/ddp/stream_server.js:16:1)
W20151123-17:41:30.476(1)? (STDERR)     at new Server (packages/ddp/livedata_server.js:1248:1)
W20151123-17:41:30.476(1)? (STDERR)     at Package (packages/ddp/server_convenience.js:19:1)
W20151123-17:41:30.476(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/packages/ddp.js:4768:4
W20151123-17:41:30.476(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/packages/ddp.js:4779:3
W20151123-17:41:30.476(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/boot.js:222:10
W20151123-17:41:30.476(1)? (STDERR)     at Array.forEach (native)
W20151123-17:41:30.477(1)? (STDERR)     at Function._.each._.forEach (/home/remi/.meteor/packages/meteor-tool/.1.0.45.10dec5p++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151123-17:41:30.477(1)? (STDERR)     at /home/remi/hckrs.io/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8  
=> Your application is crashing. Waiting for file change.

It's running in my home directory as you can see, so permissions are OK.
I'm running on ubuntu 12.04 on a 32 bit machine.

I tried to remove the .meteor/local/build directory and re-run the whole stuff but I end up with the same crash.

Am I doing something wrong ? 

I'm not a web dev so maybe an obvious dependency is missing on my machine.

Any suggestions ?

Regards,

RE

**Comment by JarnoLeConte** [comment]
I'm not sure what happened. But it seems strange that it uses the path `/home/remi/.meteor/...`, because the `.meteor` folder must be inside the project folder, so I expect `/home/remi/hckrs/.meteor/...`. Are you really inside the hckrs folder?

EDIT:
Sorry, there seems to be a `.meteor` folder in the $HOME directory as well. So that isn't the problem.

**Comment by JarnoLeConte** [comment]
Does it run when you start the application using the following command instead of `hckrs run`:

```
meteor --settings ./settings/local.json 
```

**Comment by rete** [comment]
Yes it's running but is the first part of the printout a problem ? : 

remi [18:10:29] hckrs.io $ meteor --settings ./settings/local.json
[[[[[ ~/hckrs.io ]]]]]                        

=> Started proxy.  
=> Meteor 1.2.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.  
I20151123-18:30:51.294(1)? 500 'No smtp server configured'
I20151123-18:30:51.635(1)? [MailChimp] Error: MailChimp Options have not been set in your settings.json file.
I20151123-18:30:51.775(1)? BEGIN MIGRATIONS
I20151123-18:30:51.784(1)? TASK: Hidden accounts
I20151123-18:30:51.803(1)? TASK: Complete your profile
I20151123-18:30:51.818(1)? TASK: Uninvited
I20151123-18:30:51.825(1)? TASK: Multicity with Ambassadors
I20151123-18:30:51.846(1)? TASK: Simple Schema
I20151123-18:30:51.886(1)? TASK: Simple Schema - private attribute
I20151123-18:30:51.893(1)? TASK: Ambassador
I20151123-18:30:51.901(1)? TASK: Mailings
I20151123-18:30:51.908(1)? TASK: Ambassador emails
I20151123-18:30:51.919(1)? TASK: Rename ambassador to staff
I20151123-18:30:51.925(1)? END MIGRATIONS
I20151123-18:30:51.928(1)? Mailservers aren't configured in development mode. You can ignore the warnings.
=> Started your app.

=> App running at: http://localhost:3000/
I20151123-18:30:53.929(1)? Init dummy database...
I20151123-18:30:54.563(1)? Add users for aachen
I20151123-18:30:54.583(1)? Add users for aalborg
I20151123-18:30:54.586(1)? Add users for aarhus
I20151123-18:30:54.588(1)? Add users for amsterdam
I20151123-18:30:54.592(1)? Add users for antwerpen
I20151123-18:30:54.595(1)? Add users for athens
I20151123-18:30:54.597(1)? Add users for barcelona
I20151123-18:30:54.600(1)? Add users for belfast
I20151123-18:30:54.602(1)? Add users for belgrade
I20151123-18:30:54.605(1)? Add users for bergen
I20151123-18:30:54.607(1)? Add users for berlin
I20151123-18:30:54.610(1)? Add users for bern
I20151123-18:30:54.612(1)? Add users for birmingham
I20151123-18:30:54.614(1)? Add users for bratislava
I20151123-18:30:54.617(1)? Add users for brussels
I20151123-18:30:54.620(1)? Add users for bucharest
I20151123-18:30:54.622(1)? Add users for budapest
I20151123-18:30:54.625(1)? Add users for cambridge
I20151123-18:30:54.627(1)? Add users for cardiff
I20151123-18:30:54.630(1)? Add users for chisinau
I20151123-18:30:54.632(1)? Add users for cluj-napoca
I20151123-18:30:54.634(1)? Add users for cologne
I20151123-18:30:54.637(1)? Add users for copenhagen
I20151123-18:30:54.639(1)? Add users for cork
I20151123-18:30:54.641(1)? Add users for delft
I20151123-18:30:54.643(1)? Add users for dublin
I20151123-18:30:54.646(1)? Add users for dusseldorf
I20151123-18:30:54.648(1)? Add users for eindhoven
I20151123-18:30:54.650(1)? Add users for enschede
I20151123-18:30:54.653(1)? Add users for frankfurt
I20151123-18:30:54.656(1)? Add users for galway
I20151123-18:30:54.658(1)? Add users for gdansk
I20151123-18:30:54.660(1)? Add users for geneva
I20151123-18:30:54.663(1)? Add users for gent
I20151123-18:30:54.665(1)? Add users for glasgow
I20151123-18:30:54.667(1)? Add users for gothenburg
I20151123-18:30:54.669(1)? Add users for granada
I20151123-18:30:54.671(1)? Add users for grenoble
I20151123-18:30:54.674(1)? Add users for groningen
I20151123-18:30:54.676(1)? Add users for hamburg
I20151123-18:30:54.678(1)? Add users for hannover
I20151123-18:30:54.680(1)? Add users for helsinki
I20151123-18:30:54.683(1)? Add users for hongkong
I20151123-18:30:54.686(1)? Add users for kiev
I20151123-18:30:54.688(1)? Add users for krakow
I20151123-18:30:54.691(1)? Add users for leipzig
I20151123-18:30:54.693(1)? Add users for leuven
I20151123-18:30:54.695(1)? Add users for liege
I20151123-18:30:54.698(1)? Add users for lille
I20151123-18:30:54.700(1)? Add users for limerick
I20151123-18:30:54.702(1)? Add users for lisbon
I20151123-18:30:54.705(1)? Add users for liverpool
I20151123-18:30:54.707(1)? Add users for ljubljana
I20151123-18:30:54.709(1)? Add users for london
I20151123-18:30:54.711(1)? Add users for luxembourg
I20151123-18:30:54.714(1)? Add users for lyon
I20151123-18:30:54.717(1)? Add users for maastricht
I20151123-18:30:54.719(1)? Add users for madrid
I20151123-18:30:54.721(1)? Add users for manchester
I20151123-18:30:54.724(1)? Add users for marseille
I20151123-18:30:54.726(1)? Add users for minsk
I20151123-18:30:54.728(1)? Add users for mons
I20151123-18:30:54.742(1)? Add users for montpellier
I20151123-18:30:54.744(1)? Add users for moscow
I20151123-18:30:54.747(1)? Add users for munich
I20151123-18:30:54.749(1)? Add users for nicosia
I20151123-18:30:54.752(1)? Add users for nurnberg
I20151123-18:30:54.754(1)? Add users for oslo
I20151123-18:30:54.756(1)? Add users for oxford
I20151123-18:30:54.759(1)? Add users for paris
I20151123-18:30:54.761(1)? Add users for podgorica
I20151123-18:30:54.763(1)? Add users for poznan
I20151123-18:30:54.765(1)? Add users for prague
I20151123-18:30:54.767(1)? Add users for reykjavik
I20151123-18:30:54.769(1)? Add users for riga
I20151123-18:30:54.772(1)? Add users for rome
I20151123-18:30:54.774(1)? Add users for rotterdam
I20151123-18:30:54.777(1)? Add users for sarajevo
I20151123-18:30:54.779(1)? Add users for shanghai
I20151123-18:30:54.782(1)? Add users for sheffield
I20151123-18:30:54.784(1)? Add users for skopje
I20151123-18:30:54.786(1)? Add users for sofia
I20151123-18:30:54.788(1)? Add users for stavanger
I20151123-18:30:54.790(1)? Add users for stockholm
I20151123-18:30:54.793(1)? Add users for stuttgart
I20151123-18:30:54.795(1)? Add users for swansea
I20151123-18:30:54.797(1)? Add users for tallinn
I20151123-18:30:54.799(1)? Add users for tirana
I20151123-18:30:54.802(1)? Add users for toulouse
I20151123-18:30:54.804(1)? Add users for utrecht
I20151123-18:30:54.807(1)? Add users for varna
I20151123-18:30:54.809(1)? Add users for vienna
I20151123-18:30:54.811(1)? Add users for vilnius
I20151123-18:30:54.814(1)? Add users for warsaw
I20151123-18:30:54.816(1)? Add users for wroclaw
I20151123-18:30:54.818(1)? Add users for zagreb
I20151123-18:30:54.820(1)? Add users for zurich
I20151123-18:30:54.824(1)? Insert Users...
I20151123-18:30:57.943(1)? Insert Deals...
I20151123-18:30:57.989(1)? Insert Highlights...
I20151123-18:30:58.252(1)? Insert Places...
I20151123-18:31:00.670(1)? Done.

**Comment by JarnoLeConte** [comment]
This looks correct! 

Now in order to make it accessible through the browser you must execute a more complicated command

```
ROOT_URL=http://$IP.xip.io:3000 meteor --settings ./settings/local.json 
```

where you must replace **$IP** by your local ip address within your home network. 
In my case it is **10.0.0.2**, so the command looks like:

```
ROOT_URL=http://10.0.0.2.xip.io:3000 meteor --settings ./settings/local.json 
```

Normally, this should be figured out by the hckrs command line tool. But this script is not working on your computer or maybe your network don't allow this kind of access through the xip.org service ?

**Comment by rete** [comment]
I think I found the bug ( "feature" ? :) )
In the bash script hckrs, while determining the local ip address by running : 

IP="$( ifconfig | sed -En 's/127.0.0.1//;s/._inet (addr:|adr:)?(([0-9]_.){3}[0-9]_)._/\2/p' )"

this gives me the following result : 

$ IP="$( ifconfig | sed -En 's/127.0.0.1//;s/._inet (addr:|adr:)?(([0-9]_.){3}[0-9]_)._/\2/p' )"
$ echo $IP
$ 192.168.1.100 10.0.3.1

and I think you would expect only "10.0.3.1" since it is replaced in the url in the next line.
Am I correct ?

EDIT : It's not in hckrs but in tools/main.sh

**Comment by rete** [comment]
Tested with hardcoded ip address 10.0.3.1 and works !

**Comment by JarnoLeConte** [comment]
Yes! Correct! nice ^^

So we need to change the script in order to handle your case correctly.
But I don't know which address formats could popup in general.

**Comment by JarnoLeConte** [comment]
When you enter this command in your terminal, do you get the correct IP?

```
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
```

**Comment by rete** [comment]
No. I get nothing

**Comment by rete** [comment]
But I get something with "adr" instead of "addr" : 

ifconfig | grep -Eo 'inet (adr:)?([0-9]_.){3}[0-9]_' | grep -Eo '([0-9]_.){3}[0-9]_' | grep -v '127.0.0.1'

192.168.1.88
192.168.1.100
10.0.3.1

**Comment by JarnoLeConte** [comment]
Could you copy and paste the output from performing just the command `ifconfig` to here, then I can figure out where the other ip addresses come from.

**Comment by rete** [comment]
remi [23:48:12] ~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:2e:5f:71:19:5f  
          inet adr:192.168.1.88  Bcast:192.168.1.255  Masque:255.255.255.0
          adr inet6: fe80::a2e:5fff:fe71:195f/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Packets reçus:38435 erreurs:0 :0 overruns:0 frame:0
          TX packets:25463 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          Octets reçus:41740261 (41.7 MB) Octets transmis:3955477 (3.9 MB)
          Interruption:43 Adresse de base:0xe000 

eth1      Link encap:Ethernet  HWaddr 7c:e9:d3:5e:8c:11  
          inet adr:192.168.1.100  Bcast:192.168.1.255  Masque:255.255.255.0
          adr inet6: fe80::7ee9:d3ff:fe5e:8c11/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Packets reçus:15922 erreurs:48 :0 overruns:0 frame:325918
          TX packets:19867 errors:12 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          Octets reçus:7506916 (7.5 MB) Octets transmis:4558886 (4.5 MB)
          Interruption:19 

lo        Link encap:Boucle locale  
          inet adr:127.0.0.1  Masque:255.0.0.0
          adr inet6: ::1/128 Scope:Hôte
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          Packets reçus:53595 erreurs:0 :0 overruns:0 frame:0
          TX packets:53595 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:0 
          Octets reçus:22945580 (22.9 MB) Octets transmis:22945580 (22.9 MB)

lxcbr0    Link encap:Ethernet  HWaddr 02:f1:5d:9e:d6:8e  
          inet adr:10.0.3.1  Bcast:10.0.3.255  Masque:255.255.255.0
          adr inet6: fe80::f1:5dff:fe9e:d68e/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Packets reçus:0 erreurs:0 :0 overruns:0 frame:0
          TX packets:766 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:0 
          Octets reçus:0 (0.0 B) Octets transmis:122967 (122.9 KB)

**Comment by JarnoLeConte** [comment]
In the last commit I use a command that picks the last IP address from the list it returns. I'm not sure if this will work for everyone, but hopefully it works for you at least ^^

**Comment by rete** [comment]
Yes and no. This will depends on the number and type of network interface I have on my computer and the listing order. But of course, it fixes my problem for the moment. Thank you !

Should I have to close this issue ticket ?

**Comment by JarnoLeConte** [comment]
Yeah we need to know which network interface is in use. No idea how we can solve that problem ;) But for now I will close it.
Thanks for helping !
