### ISSUE TITLE
map is not working

### ISSUE THREAD

**Issue by maxired** [hckrs/hckrs.io#142]
Hi,

the map is not working anymore.
this looks related to a change in facebook graph api for picture

For example, when querying picture for `https://graph.facebook.com/maxence.dalmais/picture?type=large`, I got the message `(#803) Cannot query users by their username (maxence.dalmais)`

**Comment by maxired** [comment]
![screenshot from 2015-12-28 14 42 46](https://cloud.githubusercontent.com/assets/1194083/12019503/49fcbc74-ad71-11e5-8f41-502dc187da9a.png)

**Comment by maxired** [comment]
Looks like change done https://github.com/hckrs/hckrs.io/commit/40fac75bf36f08670b415d0569e9e545b9b2b3cc should also be done somewhere else

**Comment by maxired** [comment]
From what i understand, we are supposed to refresh profile picture 15 minutes after server reboot .
https://github.com/hckrs/hckrs.io/blob/fa45c009325b1d5fbf111443d96fa4ddf47e2335/server/Server.js#l34

Is the heroku server still rebooted every day ?

**Comment by ramshorst** [comment]
I can not find anything indicating that this is still the case.
@JarnoLeConte do you know this ?

**Comment by ramshorst** [comment]
This confirms API change indeed : http://stackoverflow.com/questions/30886468/facebook-cannot-query-users-by-their-username-solution

**Comment by JarnoLeConte** [comment]
We uses the new FB api already, so profile pictures should be correctly displayed for new users. Furthermore every server reboot (24 hours) the profile pictures will be updated for the existing users, but probably this goes wrong. In the server logs there are only entries of updated twitter images, probably facebook and github are skipped.

**Comment by JarnoLeConte** [comment]
I removed non-exising profile pictures.
