### ISSUE TITLE
Preloading & optimize 'highlights' images.

### ISSUE THREAD

**Issue by JarnoLeConte** [hckrs/hckrs.io#30]

**Comment by ramshorst** [comment]
I believe a good solution would be to host these on a VPS server I have, or does anyone have a better idea for free wast image hosting? (since we are not moving to modulus anymore). Would it be an FTP acces or something else like SSH ?

**Comment by JarnoLeConte** [comment]
The images of existing highlights are now scaled down and moved to the *assets.hckrs.io* server. But we still need a upload/resize process built-in. Also preloading is still a nice feature to have.

**Comment by ramshorst** [comment]
I think I might have ran into something that could be very usefull to fix this :) https://addons.heroku.com/firesize

**Comment by Dandandan** [comment]
Yes, this is quite useful for us, I think. It was also on HN, someone from that service commented that the service will be free for people that join during the beta phase.

It is also a product from Assembly, a platform to design / develop products.

**Comment by ramshorst** [comment]
Is it an option to upload these images to an FTP server from the form in the website ? (I can provide a decent FTP server with storage) Or will that be hell and do we need a S3 host or something like https://addons.heroku.com/firesize ?
