### ISSUE TITLE
Add fast-render

### ISSUE THREAD

**Issue by Dandandan** [hckrs/hckrs.io#35]
The fast-render package renders the first page fast by sending the initial data along with the other data. This does improve performance a lot.

(meteor add meteorhacks:fast-render)

**Comment by ramshorst** [comment]
I think performance is a real issue right now, @Dandandan I think you had some ideas about this, isn't it ? We did some testing some time ago, and initial loading can take up to 17 seconds. Can we reduce this ?

**Comment by Dandandan** [comment]
This can be a improvement, yes, but these issues should also considered (high priority first):

* Optimize / reduce size images
* Publish less user data
* Query performance (are all frequently used queries indexed?)
* Size of libraries -> for example jquery-ui is quite big, but used almost nowhere

**Comment by ramshorst** [comment]
Nice :)

-Reducing the image size will be adressed in issue #30.
-With reducing the user data send you mean avoiding sending the entire user information needed only on the profifile page for example? @jarnoleconte is this already the case?
-query performance, @jarnoleconte is this yet the case?
-I guess jquerry-ui is only used for the hightlights page, when we will redesign this we wil aim to only use CSS3 animations :)

Thanks for the feedback; I will separate these in different issues to make them more managable :)

**Comment by JarnoLeConte** [comment]
Fast-render is added to every route since all routes are now defined in /Routes.js. 
This means that the initial page will contain all (reactive) data, but only for the subscriptions that you specify in the onWait() handler of the route (which is not yet done for most of the routes).
See commit c53f451eb2e7206cf4d11e5fc5f5a0c3bd4e8bb4
