### ISSUE TITLE
Implement subculture and meetup page

### ISSUE THREAD

**Issue by Dandandan** [hckrs/hckrs.io#40]
For the automatic meetup systems (and meetups in general), there needs to be a cool meetup page where you can see the who/what/where of this meetup.

Toon made this cool design:

![unnamed](https://cloud.githubusercontent.com/assets/163737/4518381/4b81a870-4c88-11e4-98af-1a7e0a4a3c4e.jpg)

**Comment by ramshorst** [comment]
The latest designs
--
![subculture-redesign-01](https://cloud.githubusercontent.com/assets/5200239/6187496/6b2f1cbe-b387-11e4-8fed-9562a146ccc8.jpg)
![subculture-redesign-02](https://cloud.githubusercontent.com/assets/5200239/6187491/6b0a4588-b387-11e4-8497-fc2101baf823.jpg)
![subculture-redesign-03](https://cloud.githubusercontent.com/assets/5200239/6187493/6b2cffe2-b387-11e4-8e6c-4606dadde16c.jpg)
![subculture-redesign-04](https://cloud.githubusercontent.com/assets/5200239/6187494/6b2d5154-b387-11e4-9f48-5fc4b0e1ba3f.jpg)
![subculture-redesign-05](https://cloud.githubusercontent.com/assets/5200239/6187497/6b2f4edc-b387-11e4-9146-e0a6ec5f6c37.jpg)
![subculture-redesign-06](https://cloud.githubusercontent.com/assets/5200239/6187495/6b2df348-b387-11e4-8cc5-f4564f45ee77.jpg)
![subculture-redesign-07](https://cloud.githubusercontent.com/assets/5200239/6187492/6b1f6f6c-b387-11e4-93d4-fe10e08a6bed.jpg)
