### ISSUE TITLE
Growth enhancements

### ISSUE THREAD

**Issue by ramshorst** [hckrs/hckrs.io#63]
I think these are the thing that need to be done on the growth machine:
—(only if very easy) counter that show how the number of new results, for example directly in the button's text. 
—(only if very easy) Total city counter next to 'Github users Utrecht'.
—(only if very easy)a button to manually delete someone in the list, It's even OK if this person would reappear after a new crawling. 
—Statistics:
-open rate (number/total send emails in batch + compare it to other batches with the same subject)
-click trough rate (number of people having clicked/total send emails in batch + compare it to other batches with the same subject)
-> I think it's best if we present all numbers as 1/5 (20%).

**Comment by JarnoLeConte** [comment]
Current idea:
- Geocode Github users.
- For the current cities at hckrs.io, add all Github users within a specific range to these cities.
- Statistics about how many emails sent / how many signups etc.
- Log email batches in both the mailer and templates.
