### ISSUE TITLE
Mailing always send in Lyon

### ISSUE THREAD

**Issue by ramshorst** [hckrs/hckrs.io#68]
I openen lyon, paris and grenoble in tabs, and send a mailing to them, but they all got send to the Lyon mailing list. 

@thomasguillory — I think you did not receive anything in Paris right ?

**Comment by Jarnoleconte** [comment]
This is indeed a problem. It's only allowed to login in 1 city. Probably the mailing is sent using the city of your last opened tab.
We must rethink the proces in order to solve this.
