### ISSUE TITLE
URL on hacker profile doesn't open

### ISSUE THREAD

**Issue by Dandandan** [hckrs/hckrs.io#69]
For example on this hacker page:

http://utrecht.hckrs.io/-__-_____

It seems this is simple to fix: add `//` before the url if it doesn't include a protocol.

**Comment by Jarnoleconte** [comment]
It seems already fixed many commits ago, but we haven't release it yet to the production server. Maybe we must do more releases ;)

**Comment by ramshorst** [comment]
Haha :)
