### ISSUE TITLE
Influencers page

### ISSUE THREAD

**Issue by ramshorst** [hckrs/hckrs.io#78]
![frontpage-v7-23](https://cloud.githubusercontent.com/assets/5200239/6187174/3a2137aa-b383-11e4-8842-140247a6499f.png)

--
What do you think ?

**Comment by JarnoLeConte** [comment]
Are the yellow words just highlights or links to web sites, in the latter case which sites?

**Comment by ramshorst** [comment]
I will take care of those :)
