### ISSUE TITLE
no HTTP on URL on homepage in profile

### ISSUE THREAD

**Issue by ramshorst** [hckrs/hckrs.io#81]
Example: http://enschede.hckrs.io/-_-_--_--
![screen shot 2015-02-21 at 11 33 09](https://cloud.githubusercontent.com/assets/5200239/6313787/781f18d4-b9bd-11e4-9b78-d45ffe09870f.png)

**Comment by Dandandan** [comment]
Isn't this the same as https://github.com/hckrs/hckrs.io/issues/69 ?

**Comment by ramshorst** [comment]
You are right @Dandandan, it is indeed the same as #69. Is it still an existing problem because we still have not done a release since then @JarnoLeConte ?
