### ISSUE TITLE
Profile picture via Twitter

### ISSUE THREAD

**Issue by jimtolman** [hckrs/hckrs.io#82]
The Twitter profile picture did not appear as an option for my account, although I have a profile picture at my twitter account. See the screenshot.
![twitter_pic_not_available](https://cloud.githubusercontent.com/assets/6150810/6315752/91dc6f70-ba0c-11e4-9fea-7549f342d72f.png)
example: http://enschede.hckrs.io/-___-_-_

**Comment by jimtolman** [comment]
This problem is still occurring when I change my Twitter pic.

**Comment by JarnoLeConte** [comment]
[This URL](http://pbs.twimg.com/profile_images/572408101493731328/40BuZSNo.jpeg) shows your avatar that is stored in the hackers database. Do you still not seeing your twitter avatar? That would mean that there is something wrong with the displaying.

**Comment by jimtolman** [comment]
Okey than the picture just takes some time to appear after change

**Comment by JarnoLeConte** [comment]
Right now Twitter pictures will be updated once a day. It's a shame that Twitter don't use dynamic urls as like FB and Github do.
