### ISSUE TITLE
Map -  

### ISSUE THREAD

**Issue by daanvr** [hckrs/hckrs.io#83]
- Show all users that are not from your city on the map in a anonymous fashion. This to create a feeling of the size of hckrs.io in Europe. On country or continent zoom level, only show the cities that are populated, not all the users.
 - Make the transition for profile foto to dot on the map one zoom level higher.

**Comment by JarnoLeConte** [comment]
Implemented:
- Show profile pictures at lower zoom level (commit a7233a8c7a4d8bed689c2365ef54dcc73168c920)
- Show anonymously all hackers locations (world wide) (commit 50ac71457c51e6e7cd04807d24d77f297ed32776)
- Update the popup bubble with relevant user information (commit b5c859dd72d004174a1ba4cc02b66bfc461d96e2)
