### ISSUE TITLE
Adding invites not working

### ISSUE THREAD

**Issue by ramshorst** [hckrs/hckrs.io#84]
The counter goes back immediately after adding/subtracting invites on someone's profile!

**Comment by JarnoLeConte** [comment]
Is this still the case? I can't reproduce this error.

**Comment by ramshorst** [comment]
I cannot reproduce it so I think it is fixed!

**Comment by JarnoLeConte** [comment]
Maybe it was a connection problem to the server?
To prevent this kind of issue, we should show connection failures to the client, otherwise it can be very annoying if the site not respond well.

**Comment by ramshorst** [comment]
I don't know what this is. Let me try to connect via my iphone :)
