### ISSUE TITLE
Manage subscriptions per route

### ISSUE THREAD

**Issue by JarnoLeConte** [hckrs/hckrs.io#90]
Now the user collection is fully subscribed when loading the page, this makes the site terribly slow. So what we need to do is defining for every route which users must be loaded. Therefore we need subscription/publish handlers that only load the required users and only the fields of interest.

**Comment by ramshorst** [comment]
@Dandandan would you have time to work in this one ? It's a pretty serious one though!

**Comment by Dandandan** [comment]
Probably not this week / next week (very busy). If the issue is still open and I do have time, I may look into this :).

**Comment by ramshorst** [comment]
Thanks, sounds good @Dandandan :)
Good luck with your business!

**Comment by JarnoLeConte** [comment]
It will be nice if you could fix this @Dandandan. Some things I have already structured while working on the frontpage. This means that now all routes are located in the /Routes.js file and that all subscriptions are handled there. So there are no global subscriptions any longer. Now, almost every route contains a 'users' and 'currentUser' subscription. It should be a big improvement if that subscriptions can be replaced by smaller ones that only fetch the minimal required data.

**Comment by Dandandan** [comment]
I saw the subscriptions are already handled with a more modular approach,
nice :). Do we have a Kadira account running for a dev version or only for
the production one (we don't have a test server yet, do we?). Would be nice
to have some numbers. I'll see what I can do!

**Comment by JarnoLeConte** [comment]
I again decided to disable fast-render on most of the routes except the frontpage, because the following error message shows up the whole day: `"Server sent add for existing id"`. I tried several workarounds, but each time the error moves to other places in the code. Furthermore it is a known issue of fast-render (https://github.com/meteorhacks/fast-render#client-error-server-sent-add-for-existing-id), so I will not spend more time on this.

Maybe you come up with a solution, but otherwise you are now beware of this issue.

**Comment by Dandandan** [comment]
Okay, thanks! Could that be a problem with the "reactive" publications? 

Btw, if you didn't already knew, the next version of Meteor (among other improvements) uses compression for the data transmission, this may help also speed up our data publications.

**Comment by JarnoLeConte** [comment]
Indeed, that error has something to do with the subscriptions/publications. Especially if the router redirects to some other route where the same subscriptions will be loaded again. But it only happens when fast-render is activated on that route.

The frontpage route is the only one using fast-render right now, but it still seems problematic, because some login/logout attempts will result in errors where in most cases the user can't do anything anymore.

I'm not sure if we can solve this, or that it is indeed a problem of fast-render. I'm also not sure if my approach is right to have overlapping subscriptions such as *'users'* and *'currentUser'* that can publish the same documents, although without fast-render this will work correctly, it seems.

**Comment by Dandandan** [comment]
Ok, thanks for the info! Did you get errors on the fastRender setting on the highligths page? It makes sense to enable this one as well, as setting fastRender only makes sense when on initial page load. I don't get errors when enabling this.

**Comment by JarnoLeConte** [comment]
Errors not necessarily occur directly, you must try some login/logout attempts and try to enter the website through an invite or growth URL, because then the redirect system will be triggered. 
As far I have seen it make nog sense to enable fast-render on highlights, because it is the frontpage that redirects you to the highlights, so it has no effect. Or we must decide to do the redirecting server-side in some way. The same holds for invite/growth URL's that also not use the fast-render functionality right now.

**Comment by Dandandan** [comment]
Ah, that makes sense yes.

**Comment by JarnoLeConte** [comment]
Now, almost every day I see this error message. I'm worried about this, because after such error the site don't respond anymore. I have seen it after login, after logout, but also when viewing the admin page. I still think that it has something to do with fast-render, but maybe it are the subscriptions itself that can publish multiple times the same doc. 
![error](http://assets.hckrs.io/development/issues/%2390/Schermafbeelding%202015-03-09%20om%2020.04.28.png)

@Dandandan Can you check this too? Try to login, refresh, browser restart, all that kind of things.

**Comment by Dandandan** [comment]
Yes, I have the same problem

"Error: Server sent add for existing id: jyqBfedMzW3eTesLY"

This is the id of my account, so it seems that this error comes from the user pubsub...

**Comment by JarnoLeConte** [comment]
Okay, good to know. Do you know if it is allowed what I did to subscribe 'users' and 'currentUser' in the same route? Because both subscriptions publishes the document for the logged in user, but only the fields differs (but also overlap), so then this error make sense. Although it works right the second half of the time.

**Comment by Dandandan** [comment]
I don't know, that maybe could be it? I believe by using cursors on the server side, duplicated documents are not sent again, but maybe adding them manually causes the error?

There is also this issue, with the same error message: https://github.com/meteorhacks/fast-render/issues/80

**Comment by JarnoLeConte** [comment]
As they mentioned there, it goes wrong while updating the users collection within a rendered callback. This make also sense at *hckrs.io*, because there is some query updating the user doc that runs directly after login (only for admins). Remove that query will prevent from getting this error. 

But I already tried to wrap it in afterFlush or setTimeout of 10 seconds, but then it will result again in this error, only appearing after some delay.

**Comment by Mellowlicious** [comment]
"[But] What this means is that you can have different publications and
subscriptions with different names, and all the records will end up in the
same collection on the client. Down to the level of fields, Meteor takes
care to perform a set union among documents, such that subscriptions can
overlap - publish function that ship different fields to the client work
side by side and on the client, the document in the collection will be
the union
of the two sets of fields <http://stackoverflow.com/a/14075008/1269037>."

From
http://www.meteorpedia.com/read/Understanding_Meteor_Publish_and_Subscribe
As long as the fields do not contradict each other, it will perform a union
of the fields, so there is nothing wrong with having a generic user
subscription and one currentUser subscription with more fields.

2015-03-10 9:50 GMT+01:00 Jarno Le Conté <notifications@github.com>:

**Comment by JarnoLeConte** [comment]
Thanks @Mellowlicious for finding good references. One thing they don't mention if this is also working for manually defined publish functions instead of just returning an query/cursor. But I don't see why not if the client does the set union. 

Now that is clear, we must focus on fast-render or at our implementation that will trigger errors in that package.

**Comment by Dandandan** [comment]
BTW, another issue: by providing the publish method userData, we leak the emails of users. This is a simple fix, use this.userId on the server.

On the frontpage:
```
Users.findOne("ZRYjqoG48R895CiDZ") // no email etc.
Meteor.subscribe("currentUser", "ZRYjqoG48R895CiDZ")
Users.findOne("ZRYjqoG48R895CiDZ") // emails and other fields

**Comment by Dandandan** [comment]
I added a fix for this in #107

**Comment by Dandandan** [comment]
(I meant the security issue)

**Comment by JarnoLeConte** [comment]
I disabled fast-render in last release 57faa9cc2da75bb190b0730d4a472956326b4d96 (v3.2.4) because we must solve this error messages.

**Comment by ramshorst** [comment]
@JarnoLeConte Is this what you included in the latest 'development' branch ?

**Comment by ramshorst** [comment]
Done in last release
